ARG ARCH=frommakefile
ARG DOCKERSRC=frommakefile
ARG USERNAME=frommakefile
#
FROM ${USERNAME}/${DOCKERSRC}:${ARCH}
#
ARG PUID=1001
ARG PGID=1001
#
ENV PYDIO_SRC=/opt/pydio/pydio.zip
RUN set -xe \
    && apk add --no-cache --purge -uU \
		acl \
		bzip2 \
		curl \
		gzip \
		imagemagick \
		memcached \
		openssl \
		php7-apcu \
		php7-bcmath \
		php7-bz2 \
		php7-calendar \
		php7-ctype \
		php7-curl \
		php7-dba \
		php7-dom \
		php7-exif \
		php7-ftp \
		php7-gd \
		php7-gettext \
		php7-iconv \
		php7-imagick \
		php7-imap \
		php7-intl \
		php7-ldap \
		php7-mcrypt \
		php7-memcached \
		php7-mysqli \
		php7-mysqlnd \
		php7-opcache \
		php7-pear \
		php7-pgsql \
		php7-pspell \
		php7-snmp \
		php7-sqlite3 \
		php7-xmlrpc \
		php7-zip \
		re2c \
		rsync \
		sqlite \
		ssmtp \
		tar \
		unzip \
		wget \
		xz \
	&& apk add --no-cache \
		--repository http://nl.alpinelinux.org/alpine/edge/testing \
		php7-ssh2 \
		&& if [[ -e /usr/lib/php7/ssh2.so && ! -e /usr/lib/php7/modules/ssh2.so ]]; \
		then \
			ln -s /usr/lib/php7/ssh2.so  /usr/lib/php7/modules/ssh2.so ; \
		fi \
	&& pear install Mail_mimeDecode \
	&& sed -i \
		-e "s#\output_buffering =.*#\output_buffering = \off#g" \
		-e "s/post_max_size =.*$/post_max_size = 1560M/" \
		-e "s/upload_max_filesize =.*$/upload_max_filesize = 2048M/" \
		-e 's#;session.save_path = "/tmp"#session.save_path = "/config/sess"#g' \
		/etc/php7/php.ini \
    && mkdir -p /opt/pydio \
    && VERSION=$(curl -sX GET "https://api.github.com/repos/pydio/pydio-core/tags" \
        | awk '/name/{print $4;exit}' FS='[""]' | sed -e 's_^pydio-core-__') \
    && echo "Pydio version: ${VERSION}" > /opt/pydio/version \
    && curl -o ${PYDIO_SRC} -SL "https://download.pydio.com/pub/core/archives/pydio-core-${VERSION}.zip" \
    && rm -rf /var/cache/apk/* /tmp/*
# add local files
COPY root/ /
# ports, volumes etc from php
# ENTRYPOINT ["/init"]
