#!/usr/bin/with-contenv bash

# application specific configurations
mkdir -p /data/ # if not already mounted

if [ ! -f "/config/www/pydio/index.php" ]; then
	cd /tmp || exit
	unzip -qq ${PYDIO_SRC}
	mv pydio-*/data/* /data/
	mv pydio-* /config/www/pydio
	cd / || exit
	rm -rf /tmp/* /config/www/data
    echo "Setup pydio";
else
    echo "Found exisitng pydio";
fi

# make our folders
mkdir -p \
	/config/{log/pydio,php,sess}

# sed pydio folder locations for /data and logging
sed -i -e \
	's#define("AJXP_DATA_PATH",.*#define("AJXP_DATA_PATH", "/data");#g' \
	-i -e 's#define("AJXP_SHARED_CACHE_DIR",.*#define("AJXP_SHARED_CACHE_DIR", "/data/cache");#g' \
	-i -e 's#// define("AJXP_FORCE_LOGPATH",.*#define("AJXP_FORCE_LOGPATH", "/config/log/pydio/")\;#g' \
	/config/www/pydio/conf/bootstrap_context.php

echo "Done pydio config";

# copy php ini for user editing
[[ ! -e "/config/php/php.ini" ]] && \
	cp /etc/php7/php.ini /config/php/php.ini
cp /config/php/php.ini /etc/php7/php.ini

echo "Copied php.ini";

# setting email config file.

if [ ! -f "/config/ssmtp.conf" ]; then
	cp /defaults/ssmtp.conf /config/ssmtp.conf
	chown alpine:alpine /config/ssmtp.conf
fi
cp /config/ssmtp.conf /etc/ssmtp/ssmtp.conf

echo "Copied Ssmtp.conf";

# permissions
chown -R alpine:alpine \
    /config \
    /var/tmp/nginx \
    /config/www/pydio \
    /data

echo "Done";
